// Code generated by mockery v2.46.3. DO NOT EDIT.

package config_source

import (
	task_template "github.com/leemiyinghao/go-av1/internal/models/task_template"
	mock "github.com/stretchr/testify/mock"
)

// MockYamlTaskTemplateModel is an autogenerated mock type for the YamlTaskTemplateModel type
type MockYamlTaskTemplateModel struct {
	mock.Mock
}

type MockYamlTaskTemplateModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockYamlTaskTemplateModel) EXPECT() *MockYamlTaskTemplateModel_Expecter {
	return &MockYamlTaskTemplateModel_Expecter{mock: &_m.Mock}
}

// AsEntity provides a mock function with given fields:
func (_m *MockYamlTaskTemplateModel) AsEntity() task_template.TaskTemplate {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AsEntity")
	}

	var r0 task_template.TaskTemplate
	if rf, ok := ret.Get(0).(func() task_template.TaskTemplate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(task_template.TaskTemplate)
		}
	}

	return r0
}

// MockYamlTaskTemplateModel_AsEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AsEntity'
type MockYamlTaskTemplateModel_AsEntity_Call struct {
	*mock.Call
}

// AsEntity is a helper method to define mock.On call
func (_e *MockYamlTaskTemplateModel_Expecter) AsEntity() *MockYamlTaskTemplateModel_AsEntity_Call {
	return &MockYamlTaskTemplateModel_AsEntity_Call{Call: _e.mock.On("AsEntity")}
}

func (_c *MockYamlTaskTemplateModel_AsEntity_Call) Run(run func()) *MockYamlTaskTemplateModel_AsEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockYamlTaskTemplateModel_AsEntity_Call) Return(_a0 task_template.TaskTemplate) *MockYamlTaskTemplateModel_AsEntity_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockYamlTaskTemplateModel_AsEntity_Call) RunAndReturn(run func() task_template.TaskTemplate) *MockYamlTaskTemplateModel_AsEntity_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockYamlTaskTemplateModel creates a new instance of MockYamlTaskTemplateModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockYamlTaskTemplateModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockYamlTaskTemplateModel {
	mock := &MockYamlTaskTemplateModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
